[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "forge-std/=node_modules/forge-std/src/",
    "drosera-contracts/=node_modules/drosera-contracts/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
